### ISSUE TITLE
Please clarify tx_otaa=0

### ISSUE THREAD

**Issue by vk4tux** [rthoelen/NXCore_Icom#2]
In NXCore.ini, the first value is 1, and then the second 0. Can I have clrification on this field functionality please ?

**Comment by rthoelen** [comment]
tx_otaa = 1 - Send OTAA information sent at beginning of transmission
tx_otaa = 0 - Do not send OTAA information sent at beginning of transmission

The settings in the sample file were to illustrate what things could be set to.
This was a workaround for those with Icom radios that would mute or lock up if talking to a Kenwood radio with OTAA.  Years ago we mutually agreed we would not send OTAA with Kenwood to prevent this problem.  With the NXCM software, I tried to filter the packet so that we could send to those running Kenwood, but then not send to the larger network that would go to Icom as well.

It is sort of a moot point now that I believe ICOM released a fix for the radios and they don't lock up anymore.  So you will probably just want to set everything to 1 unless there is a good reason you are told not to.
